### ISSUE TITLE
请问中文版数据是通过机器翻译得到的吗？

### ISSUE THREAD

**Issue by acadaiaca** [carbonz0/alpaca-chinese-dataset#2]
请问中文版数据是通过机器翻译了英文版alpaca数据，还是通过什么方式转换的？
谢谢！

**Comment by zhongtao93** [comment]
同问

**Comment by carbonz0** [comment]
两位的问题非常好，目前看到的数据是机器翻译的版本，但这只是其中一部分，后续还会把直接做中文self-instruct的数据也补充上来

**Comment by acadaiaca** [comment]
> 两位的问题非常好，目前看到的数据是机器翻译的版本，但这只是其中一部分，后续还会把直接做中文self-instruct的数据也补充上来

谢谢！为你的工作点赞！
